filebeat.inputs:
- type: log
  paths:
    - /app/data/disruptions*.ndjson
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "changeme1"
  ssl.enabled: true
  ssl.verification_mode: certificate
  ssl.certificate_authorities: ["ca.crt"]
