filebeat.inputs:
- type: log
  paths:
    - /app/data/disruptions*.ndjson
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log

output.logstash:
  hosts: ["logstash:5044"]

